# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a2d8b1915761dfc1a67cbaa0892e8e3bf71e3bde9faa106e8e65641717db29fcdc87654e65931b0f65be7945660fd210880715f19f96cfdac9510d1a7582dc2

test:
  secret_key_base: 16e508d913ab455be955f0c18d3fdb9dee700399c93ec9d83a7ee50511f885418f2f5dfc9f427d0f5a5a01f4325ee9d6ce9738ad4394f3544559c5eae5199156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
